### ISSUE TITLE
Error message after saving

### ISSUE THREAD

**Issue by nhmacuk** [daveystruijk/weblab-runner#1]
When I save my changed file, the program gives the error message below and stops. Is there a way I can resolve this? (Cool program btw)
```
~/weblab-runner:master* $ node index.js --url https://weblab.tudelft.nl/ti2606/2019-2020/assignment/27871/submission/19892/view --src Solution.scala --test Test.scala
Downloaded Solution.scala, watching changes...
Downloaded Test.scala, watching changes...
Mode: Your Test (toggle using 's')
Changed: Solution.scala
(node:3160) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'click' of null
    at runTest (/home/nhmacuk/weblab-runner/index.js:71:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async StatWatcher.<anonymous> (/home/nhmacuk/weblab-runner/index.js:139:5)
(node:3160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nhmacuk** [comment]
Oops, it had to change the object name. Works great!
